/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vaszilvalentin.educore.pages.subpages;

import com.vaszilvalentin.educore.auth.CurrentUser;
import com.vaszilvalentin.educore.users.User;
import com.vaszilvalentin.educore.users.UserManager;
import com.vaszilvalentin.educore.window.WindowManager;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author vaszilvalentin
 */
public class PasswordUpdate extends javax.swing.JPanel {

    /**
     * Creates new form PasswordUpdate
     */
    
    private final WindowManager windowManager;
    
    public PasswordUpdate(WindowManager windowManager) {
        initComponents();
        this.windowManager = windowManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        topContainer = new javax.swing.JPanel();
        passLabel = new javax.swing.JLabel();
        mainContainer = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        gridPanel = new javax.swing.JPanel();
        labelPanel = new javax.swing.JPanel();
        oldLabel = new javax.swing.JLabel();
        newpassLabel = new javax.swing.JLabel();
        confirmLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        oldField = new javax.swing.JPasswordField();
        newpassField = new javax.swing.JPasswordField();
        confirmField = new javax.swing.JPasswordField();
        checkboxPanel = new javax.swing.JPanel();
        showpassBox = new javax.swing.JCheckBox();
        sendBtn = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        topContainer.setPreferredSize(new java.awt.Dimension(200, 70));
        topContainer.setLayout(new java.awt.BorderLayout());

        passLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 28)); // NOI18N
        passLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passLabel.setText("Update your password");
        topContainer.add(passLabel, java.awt.BorderLayout.PAGE_END);

        add(topContainer, java.awt.BorderLayout.PAGE_START);

        mainContainer.setLayout(new java.awt.BorderLayout());

        contentPanel.setLayout(new java.awt.BorderLayout());

        centerPanel.setLayout(new java.awt.GridBagLayout());

        gridPanel.setPreferredSize(new java.awt.Dimension(500, 250));
        gridPanel.setLayout(new java.awt.GridBagLayout());

        labelPanel.setPreferredSize(new java.awt.Dimension(130, 108));
        labelPanel.setLayout(new java.awt.GridBagLayout());

        oldLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        oldLabel.setText("Old Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        labelPanel.add(oldLabel, gridBagConstraints);

        newpassLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newpassLabel.setText("New Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        labelPanel.add(newpassLabel, gridBagConstraints);

        confirmLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmLabel.setText("Confirm New Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        labelPanel.add(confirmLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        gridPanel.add(labelPanel, gridBagConstraints);

        inputPanel.setPreferredSize(new java.awt.Dimension(150, 126));
        inputPanel.setLayout(new java.awt.GridBagLayout());

        oldField.getDocument().addDocumentListener(documentListener);
        oldField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        oldField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oldField.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        inputPanel.add(oldField, gridBagConstraints);

        newpassField.getDocument().addDocumentListener(documentListener);
        newpassField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newpassField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newpassField.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        inputPanel.add(newpassField, gridBagConstraints);

        confirmField.getDocument().addDocumentListener(documentListener);
        confirmField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmField.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        inputPanel.add(confirmField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 36;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        gridPanel.add(inputPanel, gridBagConstraints);

        checkboxPanel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkboxPanel.setLayout(new java.awt.GridBagLayout());

        showpassBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showpassBox.setText("Show Password");
        showpassBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        checkboxPanel.add(showpassBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        gridPanel.add(checkboxPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        centerPanel.add(gridPanel, gridBagConstraints);

        sendBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sendBtn.setText("Change Password");
        sendBtn.setEnabled(false);
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        centerPanel.add(sendBtn, gridBagConstraints);

        contentPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        mainContainer.add(contentPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setPreferredSize(new java.awt.Dimension(200, 70));

        backBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        backBtn.setText("Go Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        bottomPanel.add(backBtn);

        mainContainer.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        add(mainContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void showpassBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassBoxActionPerformed
        togglePasswordVisibility();
    }//GEN-LAST:event_showpassBoxActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        User user = CurrentUser.getCurrentUser();
        boolean updateState = UserManager.updateUserPassword(user.getId(), new String (oldField.getPassword()), new String (newpassField.getPassword()));
        if(updateState){
            JOptionPane.showMessageDialog(null, "Password Changed Successfully!");
            windowManager.switchToPage("Settings");        
        }else {
            JOptionPane.showMessageDialog(null, "Incorrect old password!");
        }
    }//GEN-LAST:event_sendBtnActionPerformed
    
    // Toggle password visibility (show/hide)
    private void togglePasswordVisibility() {
        if (showpassBox.isSelected()) {
            newpassField.setEchoChar((char) 0); // Show password
        } else {
            newpassField.setEchoChar('•'); // Hide password
        }
    }
    
    private void checkFields() {
        String oldPassword = new String(oldField.getPassword());
        String newPassword = new String(newpassField.getPassword());
        String confirmPassword = new String(confirmField.getPassword());

        boolean isEnabled = !oldPassword.isEmpty() && newPassword.equals(confirmPassword) && !newPassword.isEmpty();
        sendBtn.setEnabled(isEnabled);
    }
    
    DocumentListener documentListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                checkFields();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkFields();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                checkFields();
            }
        };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel checkboxPanel;
    private javax.swing.JPasswordField confirmField;
    private javax.swing.JLabel confirmLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel gridPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JPanel labelPanel;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPasswordField newpassField;
    private javax.swing.JLabel newpassLabel;
    private javax.swing.JPasswordField oldField;
    private javax.swing.JLabel oldLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JButton sendBtn;
    private javax.swing.JCheckBox showpassBox;
    private javax.swing.JPanel topContainer;
    // End of variables declaration//GEN-END:variables
}
