/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vaszilvalentin.educore.pages.subpages;

import com.vaszilvalentin.educore.window.WindowManager;

/**
 *
 * @author vaszilvalentin
 */
public class PasswordUpdate extends javax.swing.JPanel {

    /**
     * Creates new form PasswordUpdate
     */
    public PasswordUpdate(WindowManager windowManager) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        topContainer = new javax.swing.JPanel();
        passLabel = new javax.swing.JLabel();
        mainContainer = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        labelPanel = new javax.swing.JPanel();
        oldLabel = new javax.swing.JLabel();
        newpassLabel = new javax.swing.JLabel();
        confirmLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        topContainer.setPreferredSize(new java.awt.Dimension(200, 70));
        topContainer.setLayout(new java.awt.BorderLayout());

        passLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 28)); // NOI18N
        passLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passLabel.setText("Update your password");
        topContainer.add(passLabel, java.awt.BorderLayout.PAGE_END);

        add(topContainer, java.awt.BorderLayout.PAGE_START);

        mainContainer.setLayout(new java.awt.BorderLayout());

        contentPanel.setLayout(new java.awt.BorderLayout());

        centerPanel.setLayout(new java.awt.GridBagLayout());

        labelPanel.setLayout(new java.awt.GridBagLayout());

        oldLabel.setText("Old Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        labelPanel.add(oldLabel, gridBagConstraints);

        newpassLabel.setText("New Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        labelPanel.add(newpassLabel, gridBagConstraints);

        confirmLabel.setText("Confirm New Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        labelPanel.add(confirmLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        centerPanel.add(labelPanel, gridBagConstraints);

        inputPanel.setLayout(new java.awt.GridBagLayout());

        jTextField1.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        inputPanel.add(jTextField1, gridBagConstraints);

        jTextField2.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        inputPanel.add(jTextField2, gridBagConstraints);

        jTextField3.setText("jTextField3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        inputPanel.add(jTextField3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        centerPanel.add(inputPanel, gridBagConstraints);

        contentPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        jButton1.setText("jButton1");
        contentPanel.add(jButton1, java.awt.BorderLayout.SOUTH);

        mainContainer.add(contentPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setPreferredSize(new java.awt.Dimension(200, 70));

        backBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        backBtn.setText("Go Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        bottomPanel.add(backBtn);

        mainContainer.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        add(mainContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel confirmLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel labelPanel;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JLabel newpassLabel;
    private javax.swing.JLabel oldLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPanel topContainer;
    // End of variables declaration//GEN-END:variables
}
