/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vaszilvalentin.educore.pages;

import com.vaszilvalentin.educore.auth.CurrentUser;
import com.vaszilvalentin.educore.preference.PreferenceManager;
import com.vaszilvalentin.educore.preference.Theme;
import com.vaszilvalentin.educore.window.WindowManager;

/**
 *
 * @author vaszilvalentin
 */
public class SettingsPage extends javax.swing.JPanel {

    /**
     * Creates new form SettingsPage
     */
    
    private final WindowManager windowManager;
    
    public SettingsPage(WindowManager windowManager) {
        initComponents();
        this.windowManager = windowManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainContainer = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        leftBox = new javax.swing.JPanel();
        themeLabel = new javax.swing.JLabel();
        themeCBox = new javax.swing.JComboBox<>();
        rightBox = new javax.swing.JPanel();
        passLabel = new javax.swing.JLabel();
        passBtn = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        topContainer = new javax.swing.JPanel();
        settingsLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        mainContainer.setLayout(new java.awt.BorderLayout());

        contentPanel.setLayout(new java.awt.GridLayout(1, 0));

        leftBox.setLayout(new java.awt.GridBagLayout());

        themeLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        themeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        themeLabel.setText("Theme selector");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        leftBox.add(themeLabel, gridBagConstraints);

        themeCBox.removeAllItems();
        for (Theme theme : Theme.values()){themeCBox.addItem(theme);}
        Theme currentTheme = PreferenceManager.loadTheme();
        themeCBox.setSelectedItem(currentTheme);
        themeCBox.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        themeCBox.setMinimumSize(new java.awt.Dimension(150, 100));
        themeCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeCBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        leftBox.add(themeCBox, gridBagConstraints);

        contentPanel.add(leftBox);

        rightBox.setLayout(new java.awt.GridBagLayout());

        passLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        passLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passLabel.setText("Change password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        rightBox.add(passLabel, gridBagConstraints);

        passBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        passBtn.setText("GO");
        passBtn.setMinimumSize(new java.awt.Dimension(150, 150));
        passBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        rightBox.add(passBtn, gridBagConstraints);

        contentPanel.add(rightBox);

        mainContainer.add(contentPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setPreferredSize(new java.awt.Dimension(200, 70));

        homeBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        homeBtn.setText("Go to Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        bottomPanel.add(homeBtn);

        mainContainer.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        add(mainContainer, java.awt.BorderLayout.CENTER);

        topContainer.setPreferredSize(new java.awt.Dimension(200, 50));
        topContainer.setLayout(new java.awt.BorderLayout());

        settingsLabel.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        settingsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsLabel.setText("Settings");
        settingsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        topContainer.add(settingsLabel, java.awt.BorderLayout.SOUTH);

        add(topContainer, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void themeCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeCBoxActionPerformed
        Theme selectedTheme = (Theme) themeCBox.getSelectedItem();
        PreferenceManager.saveTheme(selectedTheme); // Mentés
        WindowManager.applyTheme(selectedTheme);    // Alkalmazás
    }//GEN-LAST:event_themeCBoxActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        windowManager.switchToPage(CurrentUser.isLoggedIn() ? "Home" : "Landing");
    }//GEN-LAST:event_homeBtnActionPerformed

    private void passBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passBtnActionPerformed
        windowManager.switchToPage("PasswordUpdate");
    }//GEN-LAST:event_passBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel leftBox;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JButton passBtn;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPanel rightBox;
    private javax.swing.JLabel settingsLabel;
    private javax.swing.JComboBox<Theme> themeCBox;
    private javax.swing.JLabel themeLabel;
    private javax.swing.JPanel topContainer;
    // End of variables declaration//GEN-END:variables
}
